### ISSUE TITLE
question::dynamicLM

### ISSUE THREAD

**Issue by liuyishuboo** [thehanlab/dynamicLM#4]
Thank you for developing the dynamicLM package.
Multiple duplicate monitoring data with missing values, does this package apply?
Thank you!

**Comment by anyafries** [comment]
*Duplicated data:* For the input data, there must be unique values of `id, follow-up time` (i.e., patient A can have multiple entries, but they must be at unique follow-up times. For example, covariate values at baseline and at 12 months). 

*Missing data* can be seen in two ways:
* If the missing data is from a time-varying covariate after baseline, the most recent non-missing entry will be used. 
* If the missing data is from a fixed covariate or there is no prior non-missing entry for a longitudinal covariate, then the model will drop that patient during model fitting.
