### ISSUE TITLE
question: : dynamicLM

### ISSUE THREAD

**Issue by liuyishuboo** [thehanlab/dynamicLM#5]
Thank you very much for developing the dynamicLM package. 
I don’t know that the dynamicLM package has this plan to develop shiny function, which can facilitate model deployment and visualization. If it is developed, I will thank you very much.

**Comment by anyafries** [comment]
Our primary focus is on the dynamicLM package as an R library. While integrating Shiny for interactive visualization is indeed an exciting prospect, it currently falls outside the scope of our immediate development plans.
