### ISSUE TITLE
question: dynamicLM external validation

### ISSUE THREAD

**Issue by liuyishuboo** [thehanlab/dynamicLM#7]
Hello, and thank you very much for your generous sharing. I have encountered an issue while using dynamicLM to build a supermodel. Specifically, when I set the outcome event (event) values to survival (0) and death (1), I would perform external validation, the following error is reported:

> scores_external <- score(list("cox" = supermodel3), cause=1,data = validation_test, lms = "LM")
Error in predict.dynamicLM(o, data, lms, cause) : 
  No cause should be specified for a coxph model.

I tried to remove the parameter cause and it still reports an error,for example

> scores_external <- score(list("cox" = supermodel3),data = validation_test,lms = 'LM')
Error in predict.dynamicLM(o, data, lms, cause) : 
  No cause should be specified for a coxph model.

 Could I trouble you for help? Thank you.

**Comment by anyafries** [comment]
Hi,
This is a recently found bug! I am working on fixing it. 
In the meantime, you should be able to get around it by turning your test data into a stacked data set and making the predictions before evaluating them, i.e.,

```r
# stack data
lmdata_test <- stack_data(validation_test, ...)
lmdata_test <- add_interactions(...)

# get predictions
preds_test <- predict(supermodel3, lmdata_test)

# evaluate
scores_external <- score(list("cox" = preds_test))

# view
print(scores_external)
# plot
par(mfrow=c(1,2))
plot(scores_external)
```

Please let me know if that works!

**Comment by liuyishuboo** [comment]
Thank you for updating the dynamicLM package, I have reinstalled the package and fixed my issues.
