### ISSUE TITLE
question: dynamicLM plot calibration curve

### ISSUE THREAD

**Issue by liuyishuboo** [thehanlab/dynamicLM#9]
Hello, and thank you very much for your generous sharing. I would like to modify the parameters of the calibration curve, e.g. to change the color and type of the lines, to add error lines. This is not described in the package documentation, so how can I adjust it?
Thank you.

**Comment by anyafries** [comment]
Please let me know if [this section](https://github.com/thehanlab/dynamicLM?tab=readme-ov-file#35-model-evaluationvalidation) of our tutorial answers your question. Generally, most plotting parameters can be passed to the function `calplot()`.
